### PR TITLE
Add fuzzing test against built-in array

### PR DESCRIPTION
**Pull request by dubzzz**
Related to #67 and #68 

The bugs seems really tricky and rare, I did use the option `{ numRuns: 10000 }` of `fc.assert` to make the test less flaky locally (to fail everytime).

### CODE REVIEW

**Comment by dubzzz** [comment]
Do you want me to commit the fuzzer test suite?
I can rebase the review if needed

**Comment by paldepind** [comment]
Oh. I forgot about this :sweat: 

Yes! I'd definitely like to merge this. Please rebase :smile:

**Comment by dubzzz** [comment]
I just rebased it.

If you encounter failing cases for which fast-check takes too long, please let me know.
I am still working on reducing the time it takes to shrink commands, arrays and all other data-structures. For the moment, the solution is to use `noShrink` but I am thinking on adding some kind of time limit after which shrinking will be stopped https://github.com/dubzzz/fast-check/issues/286

**Comment by paldepind** [comment]
Thanks a lot @dubzzz. This looks good to me and seems to work great :+1:

**Pull request merged**
