### PR TITLE
Add badge to display install size

### PR DESCRIPTION
**Pull request by styfle**
This adds a badge to display the npm install size

### CODE REVIEW

**Comment by paldepind** [comment]
Thank you for the PR @styfle. Packagephobia is a very neat tool! I've just released a new version of List that shrinks the install size from 652 kB to 197 kB by not including the uncompiled source and source maps. I've also used Packagephobia to discover some unnecessary bloat in one of my other npm packages. Great tool 👍 

I'm a bit worried about including the badge in the readme though. List is meant both for NodeJS and the browser. I'm afraid someone might confuse the install size with how much size List would add to someone's browser bundle (which is much less than the install size thanks to tree shaking, minifying and gzip'ing).

Do you think there is a way to include the badge further down in the readme along with some explaining text?

**Comment by functionalStoic** [comment]
I found this to be a solid idea as well and it was my first time to hear about Packagephobia. But it does seem to give a slightly worst case scenario size of a package in some cases. 

I assume prompted by this new found info I noticed another very similar size feature found on the React Downshift project using the [badge-size project](https://github.com/ngryman/badge-size) and [badgesize.io](badgesize.io).

I'm not exactly sure the best way to represent the size of List with badge-size but it is at least another option. Here are a couple screenshots of what I came across.

downshift_-_npm

ngryman_badge-size__displays_the_size_of_a_given_file_in_your_repository_

Also, here is a link to the size of the [index.js](http://img.badgesize.io/https://unpkg.com/list@2.0.12/dist/index.js?label=size&style=flat-square) within the dist folder of List

Maybe badge-size could be used to give a representation of what to expect the size to be when used with NodeJS, with a tree-shaking scenario, etc

Hope that is helpful ;-)

**Comment by paldepind** [comment]
Thanks a lot for sharing your opinion as well @functionalStoic.

As a reference `import { list } from "list"` adds around 1 kB unzipped to a Webpack bundle thanks to tree shaking. According to bundlephobia.com the size of the entire library without any tree shaking is 18.9 kB and with gzip it is 6.3 kB. The install size from packagephobia.io is 197 kB.

What about having a small table like this one?

billede

It could show the package name, version, dependencies badge, install size and maybe something powered by badge-size to show the size of the full library and the smallest size possible with tree shaking?

**Comment by styfle** [comment]
Thank you for the valuable feedback! I'm glad you were able to use Package Phobia to identify bloat 👍 

I actually have been looking at tools in this area and created a list of my findings in the [readme](https://github.com/styfle/packagephobia#readme). It might be worth looking at.

I wasn't sure which file you want to use to show the gzip size since there are quite a few in the [dist](https://cdn.jsdelivr.net/npm/list/dist/) directory.

Should I add the badge size for the `index.js` file?

**Comment by paldepind** [comment]
> I actually have been looking at tools in this area and created a list of my findings in the readme. It might be worth looking at.

I did see that one. It's a good list!

> Should I add the badge size for the `index.js` file?

Yes, I think that would be the most appropriate file. Is it possible to directly get the size from a file in the npm package?

What do you think about updating the PR to include a table like the one in the screenshot above? Something like this:

| Package | Version | Dependencies | Install size | GZIP size |
| - | - | -| -| -|
| `list` | version badge | dependency badge | Packagephobia badge | badge-size? |

I think inserting it right above the "Getting started" section would work fine.

**Comment by styfle** [comment]
@paldepind Done!

image

**Comment by paldepind** [comment]
That looks really nice! Thank you :smile:

**Pull request merged**
