### PR TITLE
Annotate pure calls with a babel plugin

### PR DESCRIPTION
**Pull request by Andarist**
This helps with 'tree-shaking' curried entry point. Works similar to `sideEffects` field in pkg.json, only `sideEffects` targets webpack@4+ and `#__PURE__` comments target uglifyJS

### CODE REVIEW

**Comment by paldepind** [comment]
I just updated the [tree-shaking test](https://github.com/funkia/list/tree/master/test/tree-shaking) to measure the effect of this.

Importing List and using the uncurried `list` and `append` results in a bundle of 3.6K. Before this PR importing the curried module and using `list` and `append` resulted in a bundle of 18K. After this PR the size is down to 3.7K. I.e. the curried module tree-shakes just as well as the default module. That is really awesome 😄 👍 

Thanks a lot for the PR @Andarist. I highly appreciate it.

**Comment by Andarist** [comment]
Really cool that you have covered this with test!

**Comment by Andarist** [comment]
After a thought - I'm a little bit surprised by this. This optimization was targeting UglifyJS - webpack@4 should already cover this with its `sideEffects` feature. So not sure why this yielded better results for webpack@4 than the setup before this PR. Need to dig into this later.

**Comment by paldepind** [comment]
> Really cool that you have covered this with test!

Thank you. The readme brags about tree-shaking support so I had to make sure it actually works 😉 

> After a thought - I'm a little bit surprised by this. This optimization was targeting UglifyJS - webpack@4 should already cover this with its `sideEffects` feature. So not sure why this yielded better results for webpack@4 than the setup before this PR. Need to dig into this later.

It makes sense to me I think. Webpack 4 only uses `sideEffects` to completely get rid of things at a "module level". It is mostly useful when some file `a` re-exports from another file `b` and someone import `a` but without using any of the reexports from `b`. Then Webpack can eliminate `b` completely if the module has no side-effects. But Webpack still uses UglifyJS to shake away unused things in each module that gets included. Previously it couldn't because of the `curry2`/`curry3` calls in [src/curried.ts](https://github.com/funkia/list/blob/master/src/curried.ts) blocked it but now it can.

**Comment by Andarist** [comment]
My [previous tests on ramda](https://github.com/ramda/ramda/pull/2254#issuecomment-329983264) led me to conclusion that `sideEffects`'s goal is the same as `#__PURE__` annotations - only the approach is different. 

Reading [webpack's docs about tree-shaking](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free) it also seems it should solve this issue, however hard to tell what **exactly** this is doing as the description is not very technical.

I'm trying different configs and pkg.json setups atm but cannot yet grok how it is supposed to work, anyhow I think it's somewhat broken, just need to create a reliable repro and gonna report this to webpack team.

> But Webpack still uses UglifyJS to shake away unused things in each module that gets included. Previously it couldn't because of the curry2/curry3 calls in src/curried.ts blocked it but now it can.

That's certainly true to some extent, but to my understanding things got a little bit different in webpack@4 - I think it is supposed to actually remove some dead exports whereas in the past it relied completely on uglifyJS (webpack only removed assignments to exports object).

**Comment by paldepind** [comment]
> My previous tests on ramda led me to conclusion that sideEffects's goal is the same as #__PURE__ annotations - only the approach is different.

That was not my impression. I cannot remember exactly where I read about it. But I found something in [this blog post](https://medium.com/webpack/webpack-4-beta-try-it-today-6b1d27d7d7e2):

> We introduced support for sideEffects: false in package.json. When this field is added, it signals to webpack that there are no sideEffects in the library being consumed. This means that webpack can safely eliminate any used re-exports from your code.

Note how the quote specifically mention eliminating _re-exports_.

Maybe I can explain why you saw that with Ramda: Ramda has one index file that reexports all the functions. So it fits exactly into the case that I mentioned in my last comment. One file`index.js` re-exports from a bunch of other files. If those re-exports are not used at all by the person importing `index.js` then Webpack will, get rid of the re-exports and thus the modules altogether. This works for Ramda because `one function = one file`. But to actually remove stuff from each module Webpack still relies completely on Uglify.

**Pull request merged**
