### PR TITLE
Adjusted sideEffects, specify fantasy-land & methods as effectful

### LINKED ISSUE #8: Reconsider - sideEffects: false
Im not sure about exact algo of how it works just yet, but I suspect that this field is unsafe at the moment because, while main entry has no side effects and this package.json field can be used safely for it, the other entries such as fantasy-land are actually effectful and might be dropped because of that.

I can check with webpack@4-beta later how it behaves.

### PR DESCRIPTION
**Pull request by Andarist**
fixes #8

webpack@4 got released, i've checked quickly and for this input
```js
import * as L from "list"
import "list/fantasy-land";

console.log(L.list(0, 1, 2, 3))
```
this config
```js
const webpack = require('webpack');

module.exports = {
  devtool: false,
  optimization: {
    minimize: false,
  }
}
```
and this script
```
webpack --mode production
```

effectful fantasy-land entry was not included. I don't think more complex patterns (array, objects) are possible in sideEffects field just yet and if they are they can be added in followup PRs.

### CODE REVIEW

**Comment by paldepind** [comment]
Are we sure an array of strings is not supported? This [PR](https://github.com/webpack/webpack/pull/6536) looks like it adds support for it.

**Comment by Andarist** [comment]
I didn't see that PR, need to experiment with it once I get back home.

**Comment by Andarist** [comment]
I've tested it and it seems that we can specify:
```
"sideEffects": ["**/fantasy-land.js"],
```
and it will be preserved.

I've adjusted the PR, please take a look :)

**Comment by paldepind** [comment]
Really nice :+1: Thank you for the PR.

**Pull request merged**
